# Generated by Django 4.2.5 on 2023-11-28 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images')),
                ('fname', models.CharField(max_length=32)),
                ('lname', models.CharField(max_length=32)),
                ('emailid', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('qualification', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
